# This is a basic workflow to help you get started with Actions

name: CI

on:
    push:
        branches: [master, dev]
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              name: "Setup Node"
              with:
                  node-version: "16"
                  cache: "yarn"

            - name: "Install Dependencies"
              run: yarn --immutable

            - name: "Lint"
              run: yarn lint

            - name: "Build"
              run: yarn build
