# This is a basic workflow to help you get started with Actions

name: CI/CD

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        name: "Setup Node"
        with:
          node-version: "14"
      - name: "Install Dependencies"
        run: yarn
      - name: "Build"
        run: yarn dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: satak/webrequest-action@master
        with:
          url: ${{ secrets.PTERODACTYL_URL }}/api/client/servers/461408fc/power
          method: POST
          payload: '{"signal": "restart"}'
          headers: '{"Authorization": "Bearer ${{ secrets.PTERODACTYL_SECRET }}"}'
