# This is a basic workflow to help you get started with Actions

name: CI

on:
    push:
        branches: [master, dev]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              name: "Setup Node"
              with:
                  node-version: "16"
            - name: "Install Dependencies"
              run: yarn
            - name: "Build Bot"
              run: yarn build
