# This is a basic workflow to help you get started with Actions

name: Deploy
 
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: satak/webrequest-action@master
        with:
          url: ${{ secrets.PTERODACTYL_URL }}/api/client/servers/461408fc/power
          method: POST
          payload: '{"signal": "restart"}'
          headers: '{"Authorization": "Bearer ${{ secrets.PTERODACTYL_SECRET }}"}'
